### ISSUE TITLE
Splash/Lingering Potions

### ISSUE THREAD

**Issue by Momonche** [spigot-gillesm/RPGChest-Premium#11]
Hello Gilles !

I try to make a Splash potion but that doesn't work

With a Potion it works fine : 

```
RP_6:
  Min: 3
  Max: 3
  Items:
    SPLASH_POTION:
      Material: POTION
      Effect: INSTANT_HEAL
      Upgraded: true
      Extended: false
      Chance: 1
      Min: 1
      Max: 1
    ENCHANTED_GOLDEN_APPLE:
      Material: ENCHANTED_GOLDEN_APPLE
      Chance: 1
      Min: 1
      Max: 1
    ENDER_PEARL:
      Material: ENDER_PEARL
      Chance: 1
      Min: 1
      Max: 1
```
![s14yCgG](https://user-images.githubusercontent.com/37519498/72825518-7599a600-3c77-11ea-977a-3d3fb99453a1.png)

But with a splash potion it doesn't work

```
RP_6:
  Min: 3
  Max: 3
  Items:
    SPLASH_POTION:
      Material: SPLASH_POTION
      Effect: INSTANT_HEAL
      Upgraded: true
      Extended: false
      Chance: 1
      Min: 1
      Max: 1
    ENCHANTED_GOLDEN_APPLE:
      Material: ENCHANTED_GOLDEN_APPLE
      Chance: 1
      Min: 1
      Max: 1
    ENDER_PEARL:
      Material: ENDER_PEARL
      Chance: 1
      Min: 1
      Max: 1
```
![vAs7i67](https://user-images.githubusercontent.com/37519498/72825683-bf828c00-3c77-11ea-89d7-1e81bf4896af.png)
