### ISSUE TITLE
Empty lore on items.yml

### ISSUE THREAD

**Issue by Momonche** [spigot-gillesm/RPGChest-Premium#25]
Hello !

I just realise there is an empty lore on enchanted armor

items.yml
```
generated_9:
  material: DIAMOND_CHESTPLATE
  enchantments:
    PROTECTION_ENVIRONMENTAL: 4
    THORNS: 3
```

table.yml
```
    item18:
      Material: generated_9
      Chance: 1
      Min: 1
      Max: 1
```

When I use /data get entity @s SelectedItem, on a RPGChest item :
![pIvaqPYJEZtr](https://user-images.githubusercontent.com/37519498/83041097-60c38980-a040-11ea-9f0f-dd72be37fa54.png)

Same command on same vanilla item :
![Pr4CpGv2yheV](https://user-images.githubusercontent.com/37519498/83041213-8781c000-a040-11ea-9388-d03b87cdf8f0.png)

That empty lore broke many systems on my server cause the item is not 
recognized

Note : Maybe there is this empty lore on enchanted tools too
