### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by Momonche** [spigot-gillesm/RPGChest-Premium#26]
Hello  !

Actually when an item is wrongly define there is this error
```
/!\[RPG Chest]/!\ KelernCaravane item table stopped generating its item for performance's sake as it tried to do it more than 30 times the amount of items
/!\[RPG Chest]/!\ Please make sure KelernCaravane item table is properly configured
```

But it's impossible to know what item exacly is wrongly define and I have very, very, very long table

Can you make something to have better errors messages ?

**Comment by spigot-gillesm** [comment]
Hello,

This error is generated when it takes too many attempts to put items in a container. Can you tell me what's the minimum and maximum amount of this item table? If the problem comes from the items I'll try to improve the error messages

**Comment by Momonche** [comment]
```
KelernCaravane:
  Min: 10
  Max: 10
  Items:
    IRON_SWORD:
      Material: IRON_SWORD
      Chance: 1
      Min: 1
      Max: 1
    IRON_SWORD2:
      Material: IRONSWORD2
      Chance: 1
      Min: 1
      Max: 1
    IRON_BOOTS:
      Material: IRON_BOOTS
      Chance: 1
      Min: 1
      Max: 1
    IRON_BOOTS2:
      Material: IRONBOOTS2
      Chance: 1
      Min: 1
      Max: 1
    IRON_LEGGINGS:
      Material: IRON_LEGGINGS
      Chance: 1
      Min: 1
      Max: 1
    IRON_LEGGINGS2:
      Material: IRONLEGGINGS2
      Chance: 1
      Min: 1
      Max: 1
    IRON_CHESTPLATE:
      Material: IRON_CHESTPLATE
      Chance: 1
      Min: 1
      Max: 1
    IRON_CHESTPLATE2:
      Material: IRONCHESTPLATE2
      Chance: 1
      Min: 1
      Max: 1
    IRON_HELMET:
      Material: IRON_HELMET
      Chance: 1
      Min: 1
      Max: 1
    IRON_HELMET2:
      Material: IRONHELMET2
      Chance: 1
      Min: 1
      Max: 1
```

```
IRONSWORD2:
  material: IRON_SWORD
IRONBOOTS2:
  material: IRON_BOOTS
IRONLEGGINGS2:
  material: IRON_LEGGINGS
IRONCHESTPLATE2:
  material: IRON_CHESTPLATE
IRONHELMET2:
  material: IRON_HELMET
```

There is my table, I don't remerber why I made IRONARMOR2 but seems to be right
