### ISSUE TITLE
Make an Enchanted Book

### ISSUE THREAD

**Issue by Momonche** [spigot-gillesm/RPGChest-Premium#9]
Hello Gilles !

I try to make an enchanted book in a RPGChest but I can't

I try with items.yml like this : 

```
BOOK_UNBREAKING_3:
  Material: ENCHANTED_BOOK
  Enchantments:
    DURABILITY: 3
```

But it give a no-functionable enchanted book
![A1GWyYJ](https://user-images.githubusercontent.com/37519498/72685812-f6c53180-3aed-11ea-9c49-c0185894a79c.png)

Maybe there is a way like make potion in tables.yml but no information on the wiki ?

Server git-Paper-58 (MC 1.15.1)
RPGChest 1.9.0.3
